package com.ff.auction.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.lang.NonNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.ff.auction.dto.CreateAuctionDto;

@DynamoDBTable(tableName = "AuctionLeague")
public class AuctionLeague implements Serializable {

	private static final long serialVersionUID = 1L;

	private String leagueId;
	private String leagueName;
	private String draftTurn = "1";
	private String draftRound = "1";
	private String ppr;
	private String maxPlayers;
	private String budget = "0";
	private String status;
	private String leagueType = "Auction";
	private String currentBid = "";
	private String currentBidder = "";
	private String currentPlayer = "";

	private List<AuctionTeam> auctionTeams = new ArrayList<>();

	public AuctionLeague() {
	}

	public AuctionLeague(CreateAuctionDto createAuctionDto) {
		this.leagueName = createAuctionDto.getLeagueName();
		this.ppr = createAuctionDto.getPpr();
		this.budget = createAuctionDto.getBudget();
		this.maxPlayers = createAuctionDto.getMaxPlayers();
		this.status = "Created";
	}

	// Getters
	@NonNull
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getLeagueId() {
		return leagueId;
	}
	@DynamoDBAttribute
	public String getCurrentPlayer() {
		return this.currentPlayer;
	}
	@DynamoDBAttribute
	public String getLeagueName() {
		return this.leagueName;
	}

	@DynamoDBAttribute
	public String getPpr() {
		return this.ppr;
	}

	@DynamoDBAttribute
	public String getBudget() {
		return this.budget;
	}

	@DynamoDBAttribute
	public String getMaxPlayers() {
		return this.maxPlayers;
	}

	@DynamoDBAttribute
	public List<AuctionTeam> getAuctionTeams() {
		return this.auctionTeams;
	}

	@DynamoDBAttribute
	public String getDraftTurn() {
		return this.draftTurn;
	}

	@DynamoDBAttribute
	public String getDraftRound() {
		return this.draftRound;
	}

	@DynamoDBAttribute
	public String getStatus() {
		return this.status;
	}

	@DynamoDBAttribute
	public String getLeagueType() {
		return this.leagueType;
	}

	@DynamoDBAttribute
	public String getCurrentBid() {
		return this.currentBid;
	}

	@DynamoDBAttribute
	public String getCurrentBidder() {
		return this.currentBidder;
	}
	
	public AuctionTeam getTeam(String teamName) {
		for (AuctionTeam team : this.auctionTeams) {
			if (team.getTeamName().equals(teamName)) {
				return team;
			}
		}
		return null;
	}

	// Setters

	public void addAuctionTeam(AuctionTeam auctionTeams) {
		this.auctionTeams.add(auctionTeams);
	}

	public void setCurrentPlayer(String currentPlayer) {
		this.currentPlayer = currentPlayer;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

	public void setCurrentBid(String currentBid) {
		this.currentBid = currentBid;
	}

	public void setCurrentBidder(String currentBidder) {
		this.currentBidder = currentBidder;
	}

	public void setLeagueName(String leagueName) {
		this.leagueName = leagueName;
	}

	public void setDraftTurn(String draftTurn) {
		this.draftTurn = draftTurn;
	}

	public void setAuctionTeams(List<AuctionTeam> auctionTeams) {
		this.auctionTeams = auctionTeams;
	}

	public void setDraftRound(String draftRound) {
		this.draftRound = draftRound;
	}

	public void setPpr(String ppr) {
		this.ppr = ppr;
	}

	public void setLeagueType(String leagueType) {
		this.leagueType = leagueType;
	}

	public void setBudget(String budget) {
		this.budget = budget;
	}

	public void setMaxPlayers(String maxPlayers) {
		this.maxPlayers = maxPlayers;
	}
}