package com.ff.auction.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.lang.NonNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.ff.auction.dto.CreateAuctionDto;

@DynamoDBTable(tableName = "AuctionLeague")
public class AuctionLeague implements Serializable {

	private static final long serialVersionUID = 1L;

	private String leagueId;
	private String LeagueName;
	private String DraftTurn = "1";
	private String DraftRound = "1";
	private String Ppr;
	private String MaxPlayers;
	private String Budget = "0";
	private String Status;
	private String TeamCount = "0";
	private String LeagueType = "Auction";
	private String CurrentBid = "";
	private String CurrentBidder = "";
	private String CurrentPlayer = "";

	private List<AuctionTeam> auctionTeams = new ArrayList<AuctionTeam>();

	public AuctionLeague() {
	}

	public AuctionLeague(CreateAuctionDto createAuctionDto) {
		this.LeagueName = createAuctionDto.getLeagueName();
		this.Ppr = createAuctionDto.getPpr();
		this.Budget = createAuctionDto.getBudget();
		this.MaxPlayers = createAuctionDto.getMaxPlayers();
		this.Status = "Created";
	}

	// Getters
	@NonNull
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getLeagueId() {
		return leagueId;
	}
	@DynamoDBAttribute
	public String getCurrentPlayer() {
		return this.CurrentPlayer;
	}
	@DynamoDBAttribute
	public String getLeagueName() {
		return this.LeagueName;
	}

	@DynamoDBAttribute
	public String getPpr() {
		return this.Ppr;
	}

	@DynamoDBAttribute
	public String getBudget() {
		return this.Budget;
	}

	@DynamoDBAttribute
	public String getMaxPlayers() {
		return this.MaxPlayers;
	}

	@DynamoDBAttribute
	public List<AuctionTeam> getAuctionTeams() {
		return auctionTeams;
	}

	@DynamoDBAttribute
	public String getDraftTurn() {
		return DraftTurn;
	}

	@DynamoDBAttribute
	public String getDraftRound() {
		return DraftRound;
	}

	@DynamoDBAttribute
	public String getStatus() {
		return this.Status;
	}

	@DynamoDBAttribute
	public String getLeagueType() {
		return LeagueType;
	}

	@DynamoDBAttribute
	public String getCurrentBid() {
		return CurrentBid;
	}

	@DynamoDBAttribute
	public String getCurrentBidder() {
		return CurrentBidder;
	}

	@DynamoDBAttribute
	public String getTeamCount() {
		return TeamCount;
	}

	public AuctionTeam getTeam(String teamName) {
		for (AuctionTeam team : this.auctionTeams) {
			if (team.getTeamName().equals(teamName)) {
				return team;
			}
		}
		return null;
	}

	// Setters

	public void addAuctionTeam(AuctionTeam auctionTeams) {
		this.auctionTeams.add(auctionTeams);
	}

	public void setCurrentPlayer(String currentPlayer) {
		CurrentPlayer = currentPlayer;
	}

	public void setTeamCount(String teamCount) {
		TeamCount = teamCount;
	}

	public void setStatus(String status) {
		this.Status = status;
	}

	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

	public void setCurrentBid(String currentBid) {
		CurrentBid = currentBid;
	}

	public void setCurrentBidder(String currentBidder) {
		CurrentBidder = currentBidder;
	}

	public void setLeagueName(String leagueName) {
		this.LeagueName = leagueName;
	}

	public void setDraftTurn(String draftTurn) {
		this.DraftTurn = draftTurn;
	}

	public void setAuctionTeams(List<AuctionTeam> auctionTeams) {
		this.auctionTeams = auctionTeams;
	}

	public void setName(String leagueName) {
		this.LeagueName = leagueName;
	}

	public void setDraftRound(String draftRound) {
		DraftRound = draftRound;
	}

	public void setPpr(String ppr) {
		this.Ppr = ppr;
	}

	public void setLeagueType(String leagueType) {
		LeagueType = leagueType;
	}

	public void setBudget(String budget) {
		this.Budget = budget;
	}

	public void setMaxPlayers(String maxPlayers) {
		this.MaxPlayers = maxPlayers;
	}
}