package com.ff.snake.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.lang.NonNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.ff.snake.dto.CreateSnakeDto;

@DynamoDBTable(tableName = "SnakeLeague")
public class SnakeLeague implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String leagueId;
	private String leagueName;
	private String draftTurn = "1";
	private String draftRound = "1";
    private String ppr = "";     
    private String maxPlayers;
	private String status = "Created";
	private String leagueType = "Snake";
	
    private List<SnakeTeam> snakeTeams = new ArrayList<SnakeTeam>();
    
    public SnakeLeague() {
    }
    
    public SnakeLeague(CreateSnakeDto createDto) {
    	this.leagueName = createDto.getLeagueName();
    	this.ppr = createDto.getPpr();
		this.maxPlayers =	 createDto.getMaxPlayers();
		this.status = "Created";
    }
    
    // Getters
    @NonNull
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getLeagueId() {
		return leagueId;
	}
    @DynamoDBAttribute
    public String getLeagueName() {
        return this.leagueName;
    }
	@DynamoDBAttribute
	public String getPpr() {
		return this.ppr;
	}
    @DynamoDBAttribute
    public String getMaxPlayers() {
        return this.maxPlayers;
    }
    
    @DynamoDBAttribute
	public String getDraftTurn() {
		return this.draftTurn;
	}
    @DynamoDBAttribute
   	public String getDraftRound() {
   		return this.draftRound;
   	}
    @DynamoDBAttribute
    public String getStatus() {
    	return this.status;
    }
    @DynamoDBAttribute
	public String getLeagueType() {
		return this.leagueType;
	}
    @DynamoDBAttribute
    public List<SnakeTeam> getSnakeTeams() {
    	return this.snakeTeams;
    }
	public SnakeTeam getTeam(String teamName) {
    	for (SnakeTeam team : this.snakeTeams) {
    		if (team.getTeamName() == teamName) {
    			return team;
    		}
    	}
 		return null;
    }
    
	// Setters
    
    public void addSnakeTeam(SnakeTeam snakeTeams) {
    	this.snakeTeams.add(snakeTeams);
    }

	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

	public void setLeagueName(String leagueName) {
		this.leagueName = leagueName;
	}

	public void setDraftTurn(String draftTurn) {
		this.draftTurn = draftTurn;
	}

	public void setDraftRound(String draftRound) {
		this.draftRound = draftRound;
	}

	public void setPpr(String ppr) {
		this.ppr = ppr;
	}

	public void setMaxPlayers(String maxPlayers) {
		this.maxPlayers = maxPlayers;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setLeagueType(String leagueType) {
		this.leagueType = leagueType;
	}

	public void setSnakeTeams(List<SnakeTeam> snakeTeams) {
		this.snakeTeams = snakeTeams;
	}


	
}