package com.ff.snake.domain;

import java.io.Serializable;
import java.util.List;

import org.springframework.lang.NonNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.ff.snake.dto.CreateSnakeDto;

@DynamoDBTable(tableName = "AuctionLeague")
public class SnakeLeague implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private String leagueId;
	private String LeagueName;
	private String DraftTurn = "1";
	private String DraftRound = "1";
    private String PPR;     
    private String MaxPlayers;
	private String Status = "Created";
	private String LeagueType = "Snake";
	
    private List<SnakeTeam> snakeTeams;
    
    public SnakeLeague() {
    }
    
    public SnakeLeague(CreateSnakeDto createDto) {
    	this.LeagueName = createDto.getLeagueName();
    	this.PPR = createDto.getPpr();
		this.MaxPlayers =	 createDto.getMaxPlayers();
		this.Status = "Created";
    }
    
    // Getters
    @NonNull
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getLeagueId() {
		return leagueId;
	}
    @DynamoDBAttribute
    public String getLeagueName() {
        return this.LeagueName;
    }
    @DynamoDBAttribute
    public String getPPR() {
        return this.PPR;
    } 
    @DynamoDBAttribute
    public String getMaxPlayers() {
        return this.MaxPlayers;
    }
    
    @DynamoDBAttribute
	public String getDraftTurn() {
		return DraftTurn;
	}
    @DynamoDBAttribute
   	public String getDraftRound() {
   		return DraftRound;
   	}
    @DynamoDBAttribute
    public String getStatus() {
    	return this.Status;
    }
    @DynamoDBAttribute
	public String getLeagueType() {
		return LeagueType;
	}

	public SnakeTeam getTeam(String teamName) {
    	for (SnakeTeam team : this.snakeTeams) {
    		if (team.getTeamName() == teamName) {
    			return team;
    		}
    	}
 		return null;
    }
    
	// Setters
    
    public void addAuctionTeam(SnakeTeam snakeTeams) {
    	this.snakeTeams.add(snakeTeams);
    }
	public void setStatus(String status) {
		this.Status = status;
	}
	public void setLeagueId(String leagueId) {
		this.leagueId = leagueId;
	}

	public void setLeagueName(String leagueName) {
		this.LeagueName = leagueName;
	}

	public void setDraftTurn(String draftTurn) {
		this.DraftTurn = draftTurn;
	}
	
	public void setName(String leagueName) {
		this.LeagueName = leagueName;
	}
    
	public void setDraftRound(String draftRound) {
		DraftRound = draftRound;
	}

	public void setPPR(String pPR) {
		this.PPR = pPR;
	}
    
	public void setLeagueType(String leagueType) {
		LeagueType = leagueType;
	}

	public void setMaxPlayers(String maxPlayers) {
		this.MaxPlayers = maxPlayers;
	}
}